%YAML 1.1
---
vars:
  address-groups:
    HOME_NET: "[172.20.0.0/16,172.21.0.0/16]"
    EXTERNAL_NET: "!$HOME_NET"

  port-groups:
    HTTP_PORTS: "80"
    HTTPS_PORTS: "443"

default-rule-path: /etc/suricata/rules
rule-files:
  - custom.rules

af-packet:
  - interface: eth0
    cluster-id: 99
    cluster-type: cluster_flow
    defrag: yes
    use-mmap: yes
    tpacket-v3: yes

detect-engine:
  - profile: medium
  - custom-values:
      toclient-groups: 2
      toserver-groups: 2

app-layer:
  protocols:
    tls:
      enabled: yes
    http:
      enabled: yes
    ssh:
      enabled: yes

outputs:
  - fast:
      enabled: yes
      filename: fast.log
      append: yes

  - eve-log:
      enabled: yes
      filetype: regular
      filename: eve.json
      types:
        - alert
        - http
        - dns
        - tls
        - files
        - ssh

logging:
  default-log-level: info
  outputs:
    - console:
        enabled: yes
    - file:
        enabled: yes
        filename: suricata.log
        level: info

stats:
  enabled: yes
  interval: 30 